### ISSUE TITLE
CSS @import trouble in index.html

### ISSUE THREAD

**Issue by tcriess** [GRVYDEV/Lightspeed-react#14]
In public/index.html is the line
`@import url("https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap");`
which appears in the resulting build/index.html as
`@import url(https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap);`
(the quotes are gone), which Chromium fails to parse correctly (semicolon terminates the css statement prematurely). No idea how to prevent this "optimization".

**Comment by sienki-jenki** [comment]
How did you find out about this error? There is a way to import fonts as a `<link>` instead of `@import`. Also, probably we don't need that many Poppins styles. But overall I would like to see some kind of error or information that indicates incorrect parsing.

**Comment by tcriess** [comment]
Chromium's console log says
`GET http://127.0.0.1/url(https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100 net::ERR_ABORTED 404 (Not Found)`
So, it seems that the parsing stops after the first semicolon in the url and the browser tries to import the relative path.

**Comment by sienki-jenki** [comment]
@tcriess Just for you I installed Chromium ver. 89.0.4387.0. GET request seems to be working fine, URL is parsed correctly and every font is fetched. Could you provide more information what are you exactly using?

**Comment by tcriess** [comment]
I am on Chromium 87.0.4280.141 (snap) on Ubuntu. Files are served via nginx running in an lxc container, but that does not seem to be the issue here. As far as I can tell it really is the missing quotes. In firefox, it is parsed ok, no problem there.

**Comment by sienki-jenki** [comment]
Well, I can see that URL is missing quotes, but only after build. Somehow my Chromium, Chrome and Firefox are parsing this correctly anyway. I will take a closer look at this tomorrow.

**Comment by tcriess** [comment]
#15 fixes it, thanks!
