### ISSUE TITLE
Make wsUrl configurable after build

### ISSUE THREAD

**Issue by Scrumplex** [GRVYDEV/Lightspeed-react#2]
Hey there!

I am currently packaging all components of Lightspeed for Arch Linux (for the Arch User Repository).
Did pretty well so far with -ingest and -webrtc. Now I am facing the issue, that the wsUrl is hardcoded, and can't be set by the user when packaging.

It would be nice if this wsUrl is configurable after the build.

I think a simple JSON file somewhere would be sufficient as that can be loaded with a `fetch`.

**Comment by GRVYDEV** [comment]
Hey that is awesome to hear! I am a fellow Arch user and it is kind of wild to think that I am going to have some software on the AUR. So I am not 100% sure the best way to go about this since I have not dealt with writing packaged software before so any suggestions would be great.

**Comment by Scrumplex** [comment]
So I know how [Element Web](https://github.com/vector-im/element-web) (which even packaged in the official repos on Arch) does it.

They also provide a static web app, which is then configured with a `json` file that's loaded at the user's browser.

It's fairly simple I guess:

Fetch JSON File on page load -> Use values from that -> Done!

**Comment by GRVYDEV** [comment]
> So I know how [Element Web](https://github.com/vector-im/element-web) (which even packaged in the official repos on Arch) does it.
> 
> They also provide a static web app, which is then configured with a `json` file that's loaded at the user's browser.
> 
> It's fairly simple I guess:
> 
> Fetch JSON File on page load -> Use values from that -> Done!

My concern with this is that the page will only load on the hosts computer.

**Comment by Scrumplex** [comment]
Okay so watch this:

You run `npm build` which creates you a folder called `build`.

Now in that folder you can put whatever you want (for example our json file), which will also be available through `serve` (or any web server to be exact).

So let's say we put the `config.json` into the build folder and then host that with serve.

We can then just fetch the file from the JS in the client's browser. The location is `./config.json` (seen from index.html) and that's it. It's basically available to everyone who can also access the index.html

**Comment by GRVYDEV** [comment]
OHHH that makes so much sense now hahaha that sounds great.

**Comment by Scrumplex** [comment]
If you are not already working on it I could lay my hands on it if you don't mind :D

**Comment by GRVYDEV** [comment]
> If you are not already working on it I could lay my hands on it if you don't mind :D

Go for it! I have some meetings tonight and did not get a huge amount of sleep last night so I am relaxing on coding for today
